import SeliconCase from "../assets/images/cases/iphone12-selicon.png";
import LeatherCase from "../assets/images/cases/iphone12-leather.png";
import GlassCase from "../assets/images/cases/iphone13-glass.png";

// // ! ===========================================================
// import H_img from "../assets/images/headphones/img1.png";
// import H_img2 from "../assets/images/headphones/img2.png";
// import H_img3 from "../assets/images/headphones/img3.png";

// // ! ===========================================================
// import A_img from "../assets/images/airpods/air-img.png";
// import A_img2 from "../assets/images/airpods/air-img2.png";
// import A_img3 from "../assets/images/airpods/air-img3.png";

export const selectItems = [
  {
    name: "Apple",
    values: [
      "Выбрать модель телефона",
      "Iphone 11",
      "Iphone 11 Pro",
      "Iphone 11 Pro Max",
      "Iphone 12",
      "Iphone 12 Pro",
      "Iphone 12 Pro Max",
      "Iphone 13",
      "Iphone 13 Mini",
      "Iphone 13 Pro",
      "Iphone 13 Pro Max",
      "Iphone 14",
      "Iphone 14 Max",
      "Iphone 14 Pro Max",
    ],
  },
];

export const iphone12 = [
  {
    type: "Стеклянные",
    img: GlassCase,
  },
  {
    type: "Силиконовые",
    img: SeliconCase,
  },
  {
    type: "Кожаные",
    img: LeatherCase,
  },
];

export const dataCases = [
  {
    name: "Iphone 11",
    category: "Phone Cases",
    img: "https://image.shopmoment.com/resizer?quality=75&fit=cover&width=800&gravityX=0.5&gravityY=0.5&height=952&image=https://image.shopmoment.com/general/Moment-310-199-iPhone-14-Indigo-thumbnail.jpg",
    cost: "45,000,00 UZS",
    favourite: false,
  },
  {
    name: "Iphone 11",
    category: "Phone Cases",
    img: "https://images.uzum.uz/cgkqbnnhj8j9g69bpld0/original.jpg",
    cost: "39,000,00 UZS",
    favourite: false,
  },
  {
    name: "Iphone 11",
    category: "Phone Cases",
    img: "https://images.uzum.uz/cgg6aa7hgiov1qifkbjg/original.jpg",
    cost: "60,000,00 UZS",
    favourite: false,
  },
  {
    name: "Iphone 11",
    category: "Phone Cases",
    img: "https://images.uzum.uz/ch5pv2h6i6dvgfec0af0/original.jpg",
    cost: "90,000,00 UZS",
    favourite: false,
  },

  {
    name: "Iphone 11",
    category: "Phone Cases",
    img: "https://images.uzum.uz/cfs823fhgiov1qicthhg/original.jpg",
    cost: "55,000,00 UZS",
    favourite: false,
  },

  {
    name: "Iphone 11",
    category: "Phone Cases",
    img: "https://images.uzum.uz/cgmh9nng49devoacmpt0/original.jpg",
    cost: "25,000,00 UZS",
    favourite: false,
  },

  {
    name: "Iphone 11 Pro",
    category: "Phone Cases",
    img: "https://images.uzum.uz/ch5qbd16i6dvgfec0c4g/original.jpg",
    cost: "80,000,00 UZS",
    favourite: false,
  },

  {
    name: "Iphone 11 Pro",
    category: "Phone Cases",
    img: "https://images.uzum.uz/ceepppov1htd23aj732g/original.jpg",
    cost: "80,000,00 UZS",
    favourite: false,
  },

  {
    name: "Iphone 11 Pro",
    category: "Phone Cases",
    img: "https://images.uzum.uz/cgiip9j57mg9720d4mlg/original.jpg",
    cost: "87,000,00 UZS",
    favourite: false,
  },

  {
    name: "Iphone 11 Pro",
    category: "Phone Cases",
    img: "https://images.uzum.uz/cgdf9n7hgiov1qif77dg/original.jpg",
    cost: "23,000,00 UZS",
    favourite: false,
  },

  {
    name: "Iphone 11 Pro",
    category: "Phone Cases",
    img: "https://images.uzum.uz/cgfdatfhgiov1qifg5r0/original.jpg",
    cost: "25,000,00 UZS",
    favourite: false,
  },

  {
    name: "Iphone 11 Pro",
    category: "Phone Cases",
    img: "https://images.uzum.uz/ch5qbd0bv8aj2tft6sng/original.jpg",
    cost: "446,000,00 UZS",
    favourite: false,
  },

  {
    name: "Iphone 11 Pro",
    category: "Phone Cases",
    img: "https://images.uzum.uz/ch5qbd16i6dvgfec0c4g/original.jpg",
    cost: "46,000,00 UZS",
    favourite: false,
  },

  {
    name: "Iphone 11 Pro",
    category: "Phone Cases",
    img: "https://images.uzum.uz/cgfdl37hgiov1qifgbt0/original.jpg",
    cost: "18,000,00 UZS",
    favourite: false,
  },

  {
    name: "Iphone 11 Pro Max",
    category: "Phone Cases",
    img: "https://images.uzum.uz/cg8m427g49devoaalfog/original.jpg",
    cost: "262,000,00 UZS",
    favourite: false,
  },
  {
    name: "Iphone 11 Pro Max",
    category: "Phone Cases",
    img: "https://images.uzum.uz/ce0vbo0l08kcldto27m0/original.jpg",
    cost: "6,000,00 UZS",
    favourite: false,
  },
  {
    name: "Iphone 11 Pro Max",
    category: "Phone Cases",
    img: "https://images.uzum.uz/cfvkjjfg49devoa9fv7g/original.jpg",
    cost: "59,000,00 UZS",
    favourite: false,
  },
  {
    name: "Iphone 11 Pro Max",
    category: "Phone Cases",
    img: "https://images.uzum.uz/cgfl2h7hj8j9g69b00hg/original.jpg",
    cost: "110,000,00 UZS",
    favourite: false,
  },
  {
    name: "Iphone 11 Pro Max",
    category: "Phone Cases",
    img: "https://images.uzum.uz/cfgfiot40v9uauhi2h1g/original.jpg",
    cost: "33,000,00 UZS",
    favourite: false,
  },
  {
    name: "Iphone 11 Pro Max",
    category: "Phone Cases",
    img: "https://images.uzum.uz/cg0d3rvhgiov1qidfr1g/original.jpg",
    cost: "37,000,00 UZS",
    favourite: false,
  },
  {
    name: "Iphone 11 Pro Max",
    category: "Phone Cases",
    img: "https://images.uzum.uz/ceum5i0l08k0o9qhi9b0/original.jpg",
    cost: "25,000,00 UZS",
    favourite: false,
  },
  {
    name: "Iphone 11 Pro Max",
    category: "Phone Cases",
    img: "https://images.uzum.uz/cfcbu8gv1htd23alsih0/original.jpg",
    cost: "49,000,00 UZS",
    favourite: false,
  },

  {
    name: "Iphone 12",
    category: "Phone Cases",
    img: "https://images.uzum.uz/cdaoqv3b3ho5lmur3kh0/original.jpg",
    cost: "79,000,00 UZS",
    favourite: false,
  },

  {
    name: "Iphone 12",
    category: "Phone Cases",
    img: "https://images.uzum.uz/cfv6li7hgiov1qida3qg/original.jpg",
    cost: "17,000,00 UZS",
    favourite: false,
  },

  {
    name: "Iphone 12",
    category: "Phone Cases",
    img: "https://images.uzum.uz/cgtu1jvhj8j9g69dg0m0/original.jpg",
    cost: "45,000,00 UZS",
    favourite: false,
  },

  {
    name: "Iphone 12",
    category: "Phone Cases",
    img: "https://images.uzum.uz/cd73d0bb3ho5lmuqv4pg/original.jpg",
    cost: "79,000,00 UZS",
    favourite: false,
  },
  {
    name: "Iphone 12",
    category: "Phone Cases",
    img: "https://images.uzum.uz/cevtm1ivtie1lhbgmglg/original.jpg",
    cost: "50,000,00 UZS",
    favourite: false,
  },
  {
    name: "Iphone 12",
    category: "Phone Cases",
    img: "https://images.uzum.uz/cgfhj07hgiov1qifhabg/original.jpg",
    cost: "262,000,00 UZS",
    favourite: false,
  },
  {
    name: "Iphone 12",
    category: "Phone Cases",
    img: "https://images.uzum.uz/cgk4rqj57mg9720de88g/original.jpg",
    cost: "49,000,00 UZS",
    favourite: false,
  },
  {
    name: "Iphone 12 Pro",
    category: "Phone Cases",
    img: "https://images.umarket.uz/cc9qg2mha888i5ellefg/original.jpg",
    cost: "24,000,00 UZS",
    favourite: false,
  },
  {
    name: "Iphone 12 Pro",
    category: "Phone Cases",
    img: "https://images.uzum.uz/ce2rndgl08kcldto6kn0/original.jpg",
    cost: "143,000,00 UZS",
    favourite: false,
  },
  {
    name: "Iphone 12 Pro",
    category: "Phone Cases",
    img: "https://images.uzum.uz/ci25fo3ltlh4bk4lck9g/original.jpg",
    cost: "64,000,00 UZS",
    favourite: false,
  },
  {
    name: "Iphone 12 Pro",
    category: "Phone Cases",
    img: "https://images.uzum.uz/ch5qbd0bv8aj2tft6sng/original.jpg",
    cost: "80,000,00 UZS",
    favourite: false,
  },
  {
    name: "Iphone 12 Pro",
    category: "Phone Cases",
    img: "https://images.uzum.uz/ceuijc0v1htd23akjtd0/original.jpg",
    cost: "78,000,00 UZS",
    favourite: false,
  },
  {
    name: "Iphone 12 Pro",
    category: "Phone Cases",
    img: "https://images.uzum.uz/cfvkjjfg49devoa9fv7g/original.jpg",
    cost: "80,000,00 UZS",
    favourite: false,
  },
  {
    name: "Iphone 12 Pro Max",
    category: "Phone Cases",
    img: "https://images.uzum.uz/cgikhu7g49devoac48ig/original.jpg",
    cost: "30,000,00 UZS",
    favourite: false,
  },
  {
    name: "Iphone 12 Pro Max",
    category: "Phone Cases",
    img: "https://images.uzum.uz/ci25fo3ltlh4bk4lck9g/original.jpg",
    cost: "49,000,00 UZS",
    favourite: false,
  },
  {
    name: "Iphone 12 Pro Max",
    category: "Phone Cases",
    img: "https://images.uzum.uz/cf2jca0l08k0o9qhs6rg/original.jpg",
    cost: "90,000,00 UZS",
    favourite: false,
  },
  {
    name: "Iphone 12 Pro Max",
    category: "Phone Cases",
    img: "https://images.uzum.uz/cgf9gkfhj8j9g69atdog/original.jpg",
    cost: "30,000,00 UZS",
    favourite: false,
  },
  {
    name: "Iphone 12 Pro Max",
    category: "Phone Cases",
    img: "https://images.uzum.uz/cgv8ll7hj8j9g69dnvv0/original.jpg",
    cost: "70,000,00 UZS",
    favourite: false,
  },
  {
    name: "Iphone 12 Pro Max",
    category: "Phone Cases",
    img: "https://images.uzum.uz/ce2rndgl08kcldto6kn0/original.jpg",
    cost: "143,000,00 UZS",
    favourite: false,
  },
  {
    name: "Iphone 13",
    category: "Phone Cases",
    img: "https://images.uzum.uz/cg0alv7hgiov1qidf7ag/original.jpg",
    cost: "36,000,00 UZS",
    favourite: false,
  },
  {
    name: "Iphone 13",
    category: "Phone Cases",
    img: "https://images.uzum.uz/ce2rnvivtie1lhbeejeg/original.jpg",
    cost: "143,000,00 UZS",
    favourite: false,
  },
  {
    name: "Iphone 13",
    category: "Phone Cases",
    img: "https://images.uzum.uz/cfb0j08v1htd23alogd0/original.jpg",
    cost: "69,000,00 UZS",
    favourite: false,
  },
  {
    name: "Iphone 13",
    category: "Phone Cases",
    img: "https://images.uzum.uz/cd73a43b3ho5lmuqv47g/original.jpg",
    cost: "143,000,00 UZS",
    favourite: false,
  },
  {
    name: "Iphone 13",
    category: "Phone Cases",
    img: "https://images.uzum.uz/cg3nrg7hj8j9g699bb6g/original.jpg",
    cost: "106,000,00 UZS",
    favourite: false,
  },
  {
    name: "Iphone 13",
    category: "Phone Cases",
    img: "https://images.uzum.uz/cf23s30v1htd23akstjg/original.jpg",
    cost: "49,000,00 UZS",
    favourite: false,
  },
  {
    name: "Iphone 13 Pro",
    category: "Phone Cases",
    img: "https://images.uzum.uz/cg9fcnfg49devoaaq30g/original.jpg",
    cost: "200,000,00 UZS",
    favourite: false,
  },
  {
    name: "Iphone 13 Pro",
    category: "Phone Cases",
    img: "https://images.uzum.uz/cgdip9vhgiov1qif873g/original.jpg",
    cost: "37,000,00 UZS",
    favourite: false,
  },
  {
    name: "Iphone 13 Pro",
    category: "Phone Cases",
    img: "https://images.uzum.uz/cg3nrg7hj8j9g699bb6g/original.jpg",
    cost: "106,000,00 UZS",
    favourite: false,
  },
  {
    name: "Iphone 13 Pro",
    category: "Phone Cases",
    img: "https://images.uzum.uz/cg7nvbvg49devoaahgu0/original.jpg",
    cost: "49,000,00 UZS",
    favourite: false,
  },
  {
    name: "Iphone 13 Pro",
    category: "Phone Cases",
    img: "https://images.uzum.uz/cgdipdng49devoabcc40/original.jpg",
    cost: "52,000,00 UZS",
    favourite: false,
  },
  {
    name: "Iphone 13 Pro",
    category: "Phone Cases",
    img: "https://images.uzum.uz/cgdipevg49devoabcc50/original.jpg",
    cost: "55,000,00 UZS",
    favourite: false,
  },
  {
    name: "Iphone 13 Pro Max",
    category: "Phone Cases",
    img: "https://images.uzum.uz/cg4sjafg49devoaa4is0/original.jpg",
    cost: "72,000,00 UZS",
    favourite: false,
  },
  {
    name: "Iphone 13 Pro Max",
    category: "Phone Cases",
    img: "https://images.uzum.uz/cg3n40fhgiov1qidt3qg/original.jpg",
    cost: "78,000,00 UZS",
    favourite: false,
  },
  {
    name: "Iphone 13 Pro Max",
    category: "Phone Cases",
    img: "https://images.uzum.uz/cgp68j357mg9720e8in0/original.jpg",
    cost: "109,000,00 UZS",
    favourite: false,
  },
  {
    name: "Iphone 13 Pro Max",
    category: "Phone Cases",
    img: "https://images.uzum.uz/cg3n40fhgiov1qidt3qg/original.jpg",
    cost: "72,000,00 UZS",
    favourite: false,
  },
  {
    name: "Iphone 13 Pro Max",
    category: "Phone Cases",
    img: "https://images.uzum.uz/cg3n40fhgiov1qidt3qg/original.jpg",
    cost: "609,000,00 UZS",
    favourite: false,
  },
  {
    name: "Iphone 13 Pro Max",
    category: "Phone Cases",
    img: "https://images.uzum.uz/cdqsujgl08kcldtnqb60/original.jpg",
    cost: "208,000,00 UZS",
    favourite: false,
  },
  {
    name: "Iphone 14",
    category: "Phone Cases",
    img: "https://images.uzum.uz/cff7ca2djr2oefdugj10/original.jpg",
    cost: "139,000,00 UZS",
    favourite: false,
  },
  {
    name: "Iphone 14",
    category: "Phone Cases",
    img: "https://images.uzum.uz/chf4agv5d7kom1tfk7p0/original.jpg",
    cost: "39,000,00 UZS",
    favourite: false,
  },
  {
    name: "Iphone 14",
    category: "Phone Cases",
    img: "https://images.uzum.uz/cej7p2gl08kcldtp5mk0/original.jpg",
    cost: "23,000,00 UZS",
    favourite: false,
  },
  {
    name: "Iphone 14",
    category: "Phone Cases",
    img: "https://images.uzum.uz/cffo7nkvutv7dbm90vvg/original.jpg",
    cost: "45,000,00 UZS",
    favourite: false,
  },
  {
    name: "Iphone 14",
    category: "Phone Cases",
    img: "https://images.uzum.uz/cfj2ub125kualhm89jng/original.jpg",
    cost: "160,000,00 UZS",
    favourite: false,
  },
  {
    name: "Iphone 14 Pro",
    category: "Phone Cases",
    img: "https://images.uzum.uz/chcvb7obv8as0acreso0/original.jpg",
    cost: "80,000,00 UZS",
    favourite: false,
  },
  {
    name: "Iphone 14 Pro",
    category: "Phone Cases",
    img: "https://images.uzum.uz/cfgfj2adjr2oefdull7g/original.jpg",
    cost: "93,000,00 UZS",
    favourite: false,
  },
  {
    name: "Iphone 14 Pro",
    category: "Phone Cases",
    img: "https://images.uzum.uz/cfgdgud40v9uauhi1ri0/original.jpg",
    cost: "93,000,00 UZS",
    favourite: false,
  },
  {
    name: "Iphone 14 Pro",
    category: "Phone Cases",
    img: "https://images.uzum.uz/cftkk7fg49devoa970tg/original.jpg",
    cost: "46,000,00 UZS",
    favourite: false,
  },
  {
    name: "Iphone 14 Pro",
    category: "Phone Cases",
    img: "https://images.uzum.uz/cg1doqnhj8j9g6990rd0/original.jpg",
    cost: "199,000,00 UZS",
    favourite: false,
  },
  {
    name: "Iphone 14 Pro",
    category: "Phone Cases",
    img: "https://images.uzum.uz/cfvpo87hgiov1qidd56g/original.jpg",
    cost: "70,000,00 UZS",
    favourite: false,
  },
  {
    name: "Iphone 14 Pro Max",
    category: "Phone Cases",
    img: "https://images.uzum.uz/cgfij8fhgiov1qifhgo0/original.jpg",
    cost: "72,000,00 UZS",
    favourite: false,
  },
  {
    name: "Iphone 14 Pro Max",
    category: "Phone Cases",
    img: "https://images.uzum.uz/cfrlngvhj8j9g698a2lg/original.jpg",
    cost: "35,000,00 UZS",
    favourite: false,
  },
  {
    name: "Iphone 14 Pro Max",
    category: "Phone Cases",
    img: "https://images.uzum.uz/cfplo0fhj8j9g6980220/original.jpg",
    cost: "47,000,00 UZS",
    favourite: false,
  },
  {
    name: "Iphone 14 Pro Max",
    category: "Phone Cases",
    img: "https://images.uzum.uz/cgipesj57mg9720d6nl0/original.jpg",
    cost: "229,000,00 UZS",
    favourite: false,
  },
  {
    name: "Iphone 14 Pro Max",
    category: "Phone Cases",
    img: "https://images.uzum.uz/cffo7s2djr2oefduhsd0/original.jpg",
    cost: "45,000,00 UZS",
    favourite: false,
  },
];

export const dataChargers = [
  {
    name: "Iphone 11",
    category: "Charger",
    img: "https://images.uzum.uz/chpivsbltlh4bk4kg390/original.jpg",
    cost: "309,000,00 UZS",
    favourite: false,
  },
  {
    name: "Iphone 11",
    category: "Charger",
    img: "https://images.uzum.uz/chpivsbltlh4bk4kg390/original.jpg",
    cost: "80,000,00 UZS",
    favourite: false,
  },
  {
    name: "Iphone 11",
    category: "Charger",
    img: "https://images.uzum.uz/chpivsbltlh4bk4kg390/original.jpg",
    cost: "375,000,00 UZS",
    favourite: false,
  },
  {
    name: "Iphone 11",
    category: "Charger",
    img: "https://images.uzum.uz/chpivsbltlh4bk4kg390/original.jpg",
    cost: "306,000,00 UZS",
    favourite: false,
  },
  {
    name: "Iphone 11",
    category: "Charger",
    img: "https://images.uzum.uz/chavurv3jia9r083d3bg/original.jpg",
    cost: "120,000,00 UZS",
    favourite: false,
  },
  {
    name: "Iphone 11 Pro",
    category: "Charger",
    img: "https://images.uzum.uz/cf42u88v1htd23al2ggg/original.jpg",
    cost: "90,000,00 UZS",
    favourite: false,
  },
  {
    name: "Iphone 11 Pro",
    category: "Charger",
    img: "https://images.uzum.uz/cf42u88v1htd23al2ggg/original.jpg",
    cost: "155,000,00 UZS",
    favourite: false,
  },
  {
    name: "Iphone 11 Pro",
    category: "Charger",
    img: "https://images.uzum.uz/cf42u88v1htd23al2ggg/original.jpg",
    cost: "65,000,00 UZS",
    favourite: false,
  },
  {
    name: "Iphone 11 Pro",
    category: "Charger",
    img: "https://images.uzum.uz/ch4gr67g49devoaf8290/original.jpg",
    cost: "175,000,00 UZS",
    favourite: false,
  },
  {
    name: "Iphone 11 Pro",
    category: "Charger",
    img: "https://images.uzum.uz/chdoel9maogscco899v0/original.jpg",
    cost: "131,000,00 UZS",
    favourite: false,
  },
  {
    name: "Iphone 11 Pro",
    category: "Charger",
    img: "https://images.uzum.uz/cf2lat8l08k0o9qhsgi0/original.jpg",
    cost: "75,000,00 UZS",
    favourite: false,
  },
  {
    name: "Iphone 11 Pro Max",
    category: "Charger",
    img: "https://images.uzum.uz/cgn6p4r57mg9720dstg0/original.jpg",
    cost: "299,000,00 UZS",
    favourite: false,
  },
  {
    name: "Iphone 11 Pro Max",
    category: "Charger",
    img: "https://images.uzum.uz/che9tinhj8jf3edh6m2g/original.jpg",
    cost: "350,000,00 UZS",
    favourite: false,
  },
  {
    name: "Iphone 11 Pro Max",
    category: "Charger",
    img: "https://images.uzum.uz/chd3mfv3jia9r083jrjg/original.jpg",
    cost: "48,000,00 UZS",
    favourite: false,
  },
  {
    name: "Iphone 11 Pro Max",
    category: "Charger",
    img: "https://images.uzum.uz/ch54cn7hj8j9g69elm4g/original.jpg",
    cost: "66,000,00 UZS",
    favourite: false,
  },
  {
    name: "Iphone 11 Pro Max",
    category: "Charger",
    img: "https://images.uzum.uz/chd4pj7hj8j9aj19lgig/original.jpg",
    cost: "50,000,00 UZS",
    favourite: false,
  },
  {
    name: "Iphone 12",
    category: "Charger",
    img: "https://images.uzum.uz/cg2ur5fhj8j9g6997tmg/original.jpg",
    cost: "80,000,00 UZS",
    favourite: false,
  },
  {
    name: "Iphone 12",
    category: "Charger",
    img: "https://images.uzum.uz/cd53353b3ho5lmuq75f0/original.jpg",
    cost: "102,000,00 UZS",
    favourite: false,
  },
  {
    name: "Iphone 12",
    category: "Charger",
    img: "https://images.uzum.uz/cehbj08v1htd23ajc3og/original.jpg",
    cost: "107,000,00 UZS",
    favourite: false,
  },
  {
    name: "Iphone 12",
    category: "Charger",
    img: "https://images.uzum.uz/cgn6p4r57mg9720dstg0/original.jpg",
    cost: "299,000,00 UZS",
    favourite: false,
  },
  {
    name: "Iphone 12",
    category: "Charger",
    img: "https://images.uzum.uz/cgn6p4r57mg9720dstg0/original.jpg",
    cost: "140,000,00 UZS",
    favourite: false,
  },
  {
    name: "Iphone 12 Pro",
    category: "Charger",
    img: "https://images.uzum.uz/cg9lgnvhj8j9g69a5vh0/original.jpg",
    cost: "88,000,00 UZS",
    favourite: false,
  },
  {
    name: "Iphone 12 Pro",
    category: "Charger",
    img: "https://images.uzum.uz/ch954s8bv8as0acr3680/original.jpg",
    cost: "49,000,00 UZS",
    favourite: false,
  },
  {
    name: "Iphone 12 Pro",
    category: "Charger",
    img: "https://images.uzum.uz/ce1l2vqvtie1lhbecvp0/original.jpg",
    cost: "89,000,00 UZS",
    favourite: false,
  },
  {
    name: "Iphone 12 Pro",
    category: "Charger",
    img: "https://images.uzum.uz/cgcqopfhj8j9g69ait40/original.jpg",
    cost: "119,000,00 UZS",
    favourite: false,
  },
  {
    name: "Iphone 12 Pro",
    category: "Charger",
    img: "https://images.uzum.uz/cgrt4hng49devoadospg/original.jpg",
    cost: "117,000,00 UZS",
    favourite: false,
  },
  {
    name: "Iphone 12 Pro Max",
    category: "Charger",
    img: "https://images.uzum.uz/cev52a2vtie1lhbgkhkg/original.jpg",
    cost: "99,000,00 UZS",
    favourite: false,
  },
  {
    name: "Iphone 12 Pro Max",
    category: "Charger",
    img: "https://images.uzum.uz/cdusl2ivtie1lhbe7ce0/original.jpg",
    cost: "72,000,00 UZS",
    favourite: false,
  },
  {
    name: "Iphone 12 Pro Max",
    category: "Charger",
    img: "https://images.uzum.uz/ce117vov1htd23aid6p0/original.jpg",
    cost: "72,000,00 UZS",
    favourite: false,
  },
  {
    name: "Iphone 12 Pro Max",
    category: "Charger",
    img: "https://images.uzum.uz/cgao3lng49devoaavn3g/original.jpg",
    cost: "72,000,00 UZS",
    favourite: false,
  },
  {
    name: "Iphone 12 Pro Max",
    category: "Charger",
    img: "https://images.uzum.uz/ceusma8v1htd23akksng/original.jpg",
    cost: "53,000,00 UZS",
    favourite: false,
  },
  {
    name: "Iphone 13",
    category: "Charger",
    img: "https://images.uzum.uz/cg1k4qvhj8j9g6991uog/original.jpg",
    cost: "77,000,00 UZS",
    favourite: false,
  },
  {
    name: "Iphone 13",
    category: "Charger",
    img: "https://images.uzum.uz/cgdva0vhgiov1qif8u50/original.jpg",
    cost: "51,000,00 UZS",
    favourite: false,
  },
  {
    name: "Iphone 13",
    category: "Charger",
    img: "https://images.uzum.uz/cgdva0vhgiov1qif8u50/original.jpg",
    cost: "86,000,00 UZS",
    favourite: false,
  },
  {
    name: "Iphone 13 Pro",
    category: "Charger",
    img: "https://images.uzum.uz/cgo0k1ng49devoad0gv0/original.jpg",
    cost: "60,000,00 UZS",
    favourite: false,
  },
  {
    name: "Iphone 13 Pro",
    category: "Charger",
    img: "https://images.uzum.uz/ci06nbdenntd8rfav0l0/original.jpg",
    cost: "80,000,00 UZS",
    favourite: false,
  },
  {
    name: "Iphone 13 Pro",
    category: "Charger",
    img: "https://images.uzum.uz/cg8aj57g49devoaakmng/original.jpg",
    cost: "60,000,00 UZS",
    favourite: false,
  },
  {
    name: "Iphone 13 Pro Max",
    category: "Charger",
    img: "https://images.uzum.uz/ch387ifhj8j9g69ec7kg/original.jpg",
    cost: "37,000,00 UZS",
    favourite: false,
  },
  {
    name: "Iphone 13 Pro Max",
    category: "Charger",
    img: "https://images.uzum.uz/cghgiurfkbipbv1u9jf0/original.jpg",
    cost: "81,000,00 UZS",
    favourite: false,
  },
  {
    name: "Iphone 13 Pro Max",
    category: "Charger",
    img: "https://images.uzum.uz/cfb0i3ivtie1lhbhnbo0/original.jpg",
    cost: "235,000,00 UZS",
    favourite: false,
  },
  {
    name: "Iphone 14",
    category: "Charger",
    img: "https://images.uzum.uz/cf4l5egl08k0o9qi1sfg/original.jpg",
    cost: "59,000,00 UZS",
    favourite: false,
  },
  {
    name: "Iphone 14",
    category: "Charger",
    img: "https://images.uzum.uz/cf8haf0v1htd23algcfg/original.jpg",
    cost: "79,000,00 UZS",
    favourite: false,
  },
  {
    name: "Iphone 14",
    category: "Charger",
    img: "https://images.uzum.uz/cgooh57hj8j9g69cfmug/original.jpg",
    cost: "58,000,00 UZS",
    favourite: false,
  },
  {
    name: "Iphone 14 Pro",
    category: "Charger",
    img: "https://images.uzum.uz/cf557p8v1htd23al56hg/original.jpg",
    cost: "180,000,00 UZS",
    favourite: false,
  },
  {
    name: "Iphone 14 Pro",
    category: "Charger",
    img: "https://images.uzum.uz/cgv7u0fg49devoaeca30/original.jpg",
    cost: "261,000,00 UZS",
    favourite: false,
  },
  {
    name: "Iphone 14 Pro",
    category: "Charger",
    img: "https://images.uzum.uz/cgu0537hj8j9g69dgjdg/original.jpg",
    cost: "59,000,00 UZS",
    favourite: false,
  },
  {
    name: "Iphone 14 Pro Max",
    category: "Charger",
    img: "https://images.uzum.uz/chgu8ol6sfhndlbm7geg/original.jpg",
    cost: "247,000,00 UZS",
    favourite: false,
  },
  {
    name: "Iphone 14 Pro Max",
    category: "Charger",
    img: "https://images.uzum.uz/cg70i0ng49devoaae4lg/original.jpg",
    cost: "323,000,00 UZS",
    favourite: false,
  },
  {
    name: "Iphone 14 Pro Max",
    category: "Charger",
    img: "https://images.uzum.uz/ci0ultl6sfhndlbnrhmg/original.jpg",
    cost: "139,000,00 UZS",
    favourite: false,
  },
];
